package OpenCloset::Status;

our $STATUS_REPAIR  = 6;
our $STATUS_VISIT   = 13;
our $STATUS_MEASURE = 16;
our $STATUS_SELECT  = 17;
our $STATUS_BOXING  = 18;
our $STATUS_PAYMENT = 19;

our $STATUS_FITTING_ROOM1  = 20;
our $STATUS_FITTING_ROOM2  = 21;
our $STATUS_FITTING_ROOM3  = 22;
our $STATUS_FITTING_ROOM4  = 23;
our $STATUS_FITTING_ROOM5  = 24;
our $STATUS_FITTING_ROOM6  = 25;
our $STATUS_FITTING_ROOM7  = 26;
our $STATUS_FITTING_ROOM8  = 27;
our $STATUS_FITTING_ROOM9  = 28;
our $STATUS_FITTING_ROOM10 = 29;
our $STATUS_FITTING_ROOM11 = 30;

our @ACTIVE_STATUS = (
    $STATUS_REPAIR, $STATUS_VISIT, $STATUS_MEASURE, $STATUS_SELECT,
    $STATUS_BOXING, $STATUS_PAYMENT,
    $STATUS_FITTING_ROOM1 .. $STATUS_FITTING_ROOM11
);

1;
